# Generated by Django 5.0.4 on 2024-06-20 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('Employee', 'Employee'), ('ProjectManager', 'ProjectManager'), ('Intern', 'Intern'), ('ContractEmployee', 'ContractEmployee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('madical', 'madical'), ('sick', 'sick'), ('Contract', 'Contract')], max_length=10),
        ),
    ]
