# Generated by Django 5.0.4 on 2024-06-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_customuser_role_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('madical', 'madical'), ('sick', 'sick'), ('casual', 'casual')], max_length=10),
        ),
    ]
