# Generated by Django 5.0.4 on 2024-06-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_acount_no_employee_address_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='Martial_status',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='address_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='icfc',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone_no',
            new_name='ifsc_code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='bio',
            new_name='pan_no',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='upi',
            new_name='upi_id',
        ),
    ]
