# Generated by Django 5.0.4 on 2024-06-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_attendance_employee_alter_leave_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='acount_no',
            new_name='account',
        ),
    ]
