# Generated by Django 5.0.4 on 2024-06-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_rename_acount_no_customuser_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='account',
            new_name='account_no',
        ),
    ]
