# Generated by Django 5.0.4 on 2024-06-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_remove_customuser_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], default='unmarried', max_length=40),
        ),
    ]
